class_name DataWorldSummaryPlayer
extends Resource

## 2 line string - Player color | controller name [br]
## generated by Player.get_full_player_description
@export_multiline var player_description : String = "Unknown player\n"

## either "winner" or "loser"
@export var state : String = "winner"

## description of heroes used by the player
@export_multiline var heroes : String = ""
